import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import type { ThreadSource } from '../types.js';

export interface LocalThreadMetadata {
  threadId: string;
  /** The user-facing chat name generated by Codex, never a raw prompt. */
  displayName: string | null;
  /** Raw prompt preview, used only as a fallback title. */
  preview: string | null;
  updatedAt: number;
  source: ThreadSource | null;
  sourceLabel: string | null;
  model: string | null;
  reasoningEffort: string | null;
  gitBranch: string | null;
  projectName: string | null;
  cwd: string | null;
  archived: boolean;
}

type SqliteRow = Record<string, unknown>;

const GENERIC_THREAD_SOURCES = new Set(['user', 'subagent', 'guardian_review', 'main']);

function textValue(value: unknown, maxLength = 300): string | null {
  if (typeof value !== 'string') return null;
  const normalized = value.replace(/\s+/g, ' ').trim();
  return normalized ? normalized.slice(0, maxLength) : null;
}

function timestampSeconds(value: unknown): number {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Math.round(value > 10_000_000_000 ? value / 1000 : value);
  }
  if (typeof value === 'string' && value.trim()) {
    const numeric = Number(value);
    if (Number.isFinite(numeric)) {
      return Math.round(numeric > 10_000_000_000 ? numeric / 1000 : numeric);
    }
    const parsed = Date.parse(value);
    if (Number.isFinite(parsed)) return Math.round(parsed / 1000);
  }
  return Math.floor(Date.now() / 1000);
}

function columnExpression(columns: Set<string>, candidates: string[], alias: string): string {
  const column = candidates.find((candidate) => columns.has(candidate));
  return column ? `t.${column} AS ${alias}` : `NULL AS ${alias}`;
}

/** Map Codex's `source` / `thread_source` values onto the dashboard's categories. */
export function classifyThreadSource(
  source: string | null,
  threadSource: string | null
): { source: ThreadSource; sourceLabel: string | null } {
  const rawSource = (source ?? '').toLowerCase();
  const rawThreadSource = (threadSource ?? '').toLowerCase();
  const label = threadSource && !GENERIC_THREAD_SOURCES.has(rawThreadSource) ? threadSource : null;

  if (rawSource.includes('guardian') || rawThreadSource === 'guardian_review') {
    return { source: 'review', sourceLabel: null };
  }
  if (rawSource.includes('subagent') || rawThreadSource === 'subagent') {
    return { source: 'subagent', sourceLabel: label };
  }
  if (rawThreadSource.includes('voice')) return { source: 'voice', sourceLabel: null };
  if (rawSource.includes('cloud') || rawSource.includes('remote')) {
    return { source: 'cloud', sourceLabel: label };
  }
  if (rawSource === 'exec') return { source: 'exec', sourceLabel: label };
  if (rawSource === 'cli' || rawSource === 'tui') return { source: 'cli', sourceLabel: label };
  if (rawSource === 'vscode' || rawSource === 'desktop' || rawSource.includes('codex desktop')) {
    return { source: 'desktop', sourceLabel: label };
  }
  return { source: rawSource ? 'unknown' : 'unknown', sourceLabel: label };
}

export function readLocalThreadMetadata(): LocalThreadMetadata[] {
  const codexHome = path.resolve(process.env.CODEX_HOME || path.join(os.homedir(), '.codex'));
  const statePath = path.join(codexHome, 'state_5.sqlite');
  if (!fs.existsSync(statePath)) return [];

  let database: DatabaseSync | null = null;
  try {
    database = new DatabaseSync(statePath, { readOnly: true });
    const tables = new Set(
      (database.prepare("SELECT name FROM sqlite_master WHERE type = 'table'").all() as SqliteRow[])
        .map((row) => (typeof row.name === 'string' ? row.name : null))
        .filter((name): name is string => name !== null)
    );
    if (!tables.has('threads')) return [];

    const columns = new Set(
      (database.prepare('PRAGMA table_info(threads)').all() as SqliteRow[])
        .map((row) => (typeof row.name === 'string' ? row.name : null))
        .filter((name): name is string => name !== null)
    );
    if (!columns.has('id')) return [];

    const hasProjects = tables.has('projects') && columns.has('project_id');
    const select = [
      't.id AS threadId',
      columnExpression(columns, ['name'], 'generatedName'),
      columnExpression(columns, ['title'], 'title'),
      columnExpression(columns, ['preview'], 'preview'),
      columnExpression(columns, ['first_user_message', 'firstUserMessage'], 'firstUserMessage'),
      columnExpression(columns, ['source'], 'source'),
      columnExpression(columns, ['thread_source'], 'threadSource'),
      columnExpression(columns, ['model'], 'model'),
      columnExpression(columns, ['reasoning_effort'], 'reasoningEffort'),
      columnExpression(columns, ['git_branch'], 'gitBranch'),
      columnExpression(columns, ['cwd'], 'cwd'),
      columnExpression(columns, ['archived'], 'archived'),
      columnExpression(
        columns,
        ['updated_at_ms', 'updated_at', 'recency_at_ms', 'created_at_ms', 'created_at'],
        'updatedAtValue'
      ),
      hasProjects ? 'p.name AS projectName' : 'NULL AS projectName'
    ].join(', ');
    const rows = database.prepare(`
      SELECT ${select}
      FROM threads t
      ${hasProjects ? 'LEFT JOIN projects p ON p.id = t.project_id' : ''}
    `).all() as SqliteRow[];

    return rows.flatMap((row) => {
      const threadId = textValue(row.threadId, 200);
      if (!threadId) return [];
      const classified = classifyThreadSource(
        textValue(row.source, 400),
        textValue(row.threadSource, 200)
      );
      const preview =
        textValue(row.preview, 500) ??
        textValue(row.firstUserMessage, 500) ??
        textValue(row.title, 500);
      return [{
        threadId,
        displayName: textValue(row.generatedName),
        preview,
        updatedAt: timestampSeconds(row.updatedAtValue),
        source: classified.source,
        sourceLabel: classified.sourceLabel,
        model: textValue(row.model, 100),
        reasoningEffort: textValue(row.reasoningEffort, 40),
        gitBranch: textValue(row.gitBranch, 200),
        projectName: textValue(row.projectName, 200),
        cwd: textValue(row.cwd, 500),
        archived: row.archived === 1 || row.archived === true
      }];
    });
  } catch (error) {
    if (process.env.DEBUG_CODEX_DASHBOARD === 'true') {
      console.warn('Could not read Codex desktop thread metadata:', (error as Error).message);
    }
    return [];
  } finally {
    database?.close();
  }
}
