import { cleanUserMessage } from '../messageText.js';

type JsonRecord = Record<string, unknown>;

function isRecord(value: unknown): value is JsonRecord {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Text of a user message from a Claude Code transcript. Returns null for tool
 * results (which arrive as user-role messages) and for messages with no text.
 */
export function extractClaudePromptText(content: unknown): string | null {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return null;
  const parts: string[] = [];
  for (const block of content) {
    if (!isRecord(block)) continue;
    if (block.type === 'tool_result') return null;
    if (block.type === 'text' && typeof block.text === 'string') parts.push(block.text);
  }
  return parts.length > 0 ? parts.join('\n') : null;
}

/** Wrappers Claude Code injects around things the user did not type as a prompt. */
const BLOCKED_PREFIXES = [
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<local-command-caveat>',
  '<bash-input>',
  '<bash-stdout>',
  '<bash-stderr>',
  '<user-memory-input>',
  '<task-notification>',
  'caveat: the messages below were generated by the user while running local commands',
  'this session is being continued from a previous conversation',
  '[request interrupted by user'
];

const STRIPPED_BLOCKS = [
  'system-reminder',
  'ide_selection',
  'ide_opened_file',
  'ide_diagnostics',
  'task-notification',
  'local-command-caveat',
  'attached_files'
];

function commandText(value: string): string | null {
  const name = /<command-name>([\s\S]*?)<\/command-name>/i.exec(value)?.[1]?.trim();
  if (!name) return null;
  const args = /<command-args>([\s\S]*?)<\/command-args>/i.exec(value)?.[1]?.trim() ?? '';
  return args ? `${name} ${args}` : name;
}

/**
 * Clean a Claude Code prompt for display. Shell passthrough, local command
 * output, compaction summaries, and task notifications are not prompts and
 * return null. Slash commands are rendered as `/name args`; whether they reached
 * the model is decided by the parser (a command that produced no API call is
 * dropped there). IDE context and system reminders are stripped from real prompts.
 */
export function cleanClaudePrompt(text: string, maxLength = 1000): string | null {
  let value = text.replace(/\r\n/g, '\n').trim();
  if (!value) return null;
  const lower = value.toLowerCase();
  if (BLOCKED_PREFIXES.some((prefix) => lower.startsWith(prefix))) return null;
  if (lower.startsWith('<command-name>') || lower.startsWith('<command-message>')) {
    const command = commandText(value);
    return command ? command.slice(0, maxLength) : null;
  }

  for (const tag of STRIPPED_BLOCKS) {
    const pattern = new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`, 'gi');
    value = value.replace(pattern, ' ');
  }
  value = value
    .replace(/\[Image #?\d+\]/gi, ' ')
    .trim();
  if (!value) return null;
  return cleanUserMessage(value, maxLength);
}
